### ISSUE TITLE
How to set the initial state to expanded？

### ISSUE THREAD

**Issue by meng-fucius** [aryzhov/flutter-expandable#106]
I want to expand expandable by default when the widget is created ,what shall i do?

**Comment by abhisunkewar** [comment]
Hi @meng-fucius, you can do that by assigning the `Expandable` Widget a `ExpandableController` with the `initialExpanded` parameter set to `true`. As shown below:

```dart
ExpandableController _controller = ExpandableController(initialExpanded: true);
```

**Comment by mohdosman-dev** [comment]
> Hi @meng-fucius, you can do that by assigning the `Expandable` Widget a `ExpandableController` with the `initialExpanded` parameter set to `true`. As shown below:
> 
> ```dart
> ExpandableController _controller = ExpandableController(initialExpanded: true);
> ```

Not worked for me
