### ISSUE TITLE
Icon Color

### ISSUE THREAD

**Issue by mahmudemam** [aryzhov/flutter-expandable#13]
Hello,

How do I specify a color for the icon? the default color is inherited to be black, and I want it to be another one.

**Comment by aryzhov** [comment]
Hi, I have just added the optional `iconColor` parameter to `ExapandablePanel` and released version 2.2.1.

**Comment by aryzhov** [comment]
I had to publish version 2.2.2+3 which disables this feature because this new feature depends on Flutter 1.7.3 which has not been released yet as a stable release. Please use version 2.2.1 with Flutter from the dev channel.
