### ISSUE TITLE
Nested ExpandablePanels Misbehaving

### ISSUE THREAD

**Issue by LuckierDodge** [aryzhov/flutter-expandable#15]
Tried to nest multiple ExpandablePanels inside each other today, and discovered a bit of a hiccup: if you expand the root panel, all of its children are expanded as well. Likewise, if you collapse any of the child panels, the whole tree collapses.

Is this something I could circumvent with a custom Expandable Widget?

**Comment by aryzhov** [comment]
In this case, you don't need a custom `Expandable`. What you need is to wrap your nested `ExpandablePanel` with `ExpandableNotifier`.  What's happening is `ExpandablePanel` creates an `ExpandableNotifier`, which contains the expanded state, only if it's not present in the context. So the inner `ExpandablePanel` finds the `ExpandableNotifier` of the outer `ExpandablePanel`. Wrapping it with an `ExpandableNotifier` would make it have own, independent state.

**Comment by LuckierDodge** [comment]
Worked like a charm, and with a solid explanation to boot. Thank you sir!

**Comment by aryzhov** [comment]
Glad I could help!
