### ISSUE TITLE
Expandable Notifier height

### ISSUE THREAD

**Issue by tjholic** [aryzhov/flutter-expandable#21]
How do I adjust the height the Expandable Notifier Widget when widget collapsed?

**Comment by aryzhov** [comment]
The height of `ExpandablePanel` will be adjusted automatically if the height of the `collapsed` widget changes. To control the height of your `collapsed` widget, you may use one of the layout widgets. For example:
```dart
              ConstrainedBox(
                constraints: BoxConstraints(maxHeight: 20),
              )
```
