### ISSUE TITLE
Remove splash/ripple effect on header when tapHeaderToExpand = true

### ISSUE THREAD

**Issue by topex-psy** [aryzhov/flutter-expandable#24]
In the `ExpandableButton` class, could you please replace `InkWell` with `GestureDetector`, because I don't want the ripple effect, or at least give me the option to disable the ripple effect.
Thank you in advance.

**Comment by bantunes22** [comment]
+1, i'm going to create a fork for this one.

**Comment by bantunes22** [comment]
@topex-psy  https://github.com/bantunes22/flutter-expandable

**Comment by aryzhov** [comment]
This is fixed in version 4.0.0, where `useInkWell: false` can be specified as a theme setting.
