### ISSUE TITLE
Body text alignment

### ISSUE THREAD

**Issue by mun5865** [aryzhov/flutter-expandable#32]
How to align text in "collapsed" and "expanded" to left, so far I can only align header and icon.

My code is shown below:

`ExpandablePanel(`
` ` ` header: Text("Waranty Type",style: TextStyle(fontSize: 15, color: AlleColors.marketMain),),`
` ` ` headerAlignment: ExpandablePanelHeaderAlignment.center,`
` ` ` collapsed: Text("No Warranty",style: TextStyle(color: AlleColors.textBody,), `
` ` ` textAlign: TextAlign.left,maxLines: 2,overflow: TextOverflow.ellipsis,softWrap: true,),`
` ` ` expanded: Text("No Warranty", style: TextStyle(color: AlleColors.textBody),softWrap: true),`
` ` ` tapHeaderToExpand: true,`
` ` ` tapBodyToCollapse: true,`
` ` ` iconPlacement: ExpandablePanelIconPlacement.right,`
` ` ` hasIcon: true,`
` ` `iconColor: AlleColors.marketMain,`
`),`

![1](https://user-images.githubusercontent.com/26474564/70038072-a273fa00-15f2-11ea-8fcf-daae467a83d8.JPG)

**Comment by hmayer00** [comment]
@mun5865 I'm not entirely clear on why it center-aligns by default, but you can easily override that with:
```dart
ExpandablePanel(
  //...
  collapsed: Align(alignment: Alignment.centerLeft, child: Text('foo')),
  expanded: Align(alignment: Alignment.centerLeft, child: Text('bar')),
  //...
);
```
