### ISSUE TITLE
How to implement this 2 requirements?

### ISSUE THREAD

**Issue by gzlock** [aryzhov/flutter-expandable#35]
1. Like the SliverAppBar in the NestedScrollView, the expandable header can pinned at the top position when the list scrolling down.
![2](https://user-images.githubusercontent.com/2311740/70854821-fa1c3a80-1efb-11ea-8db7-f90f0fe85b33.gif)

2. Like the [jQuery Accordion ](https://jqueryui.com/accordion/#fillspace)
![1](https://user-images.githubusercontent.com/2311740/70854474-35683a80-1ef7-11ea-8e6c-ec7dbfa7fbd3.gif)

**Comment by aryzhov** [comment]
Check out `SliverList`. The `Expandable` widget might help you to implement #1 but the implementation will not be simple. For #2 you don't need `Expandable`, you need a `SliverList` with a custom `SliverListDelegate`.

I am closing this, and please note that such questions are outside of the scope of this project. YOu may want to post this on StackOverflow.
