### ISSUE TITLE
Specifying controller for ExpandablePanel causes runtime error

### ISSUE THREAD

**Issue by atessift** [aryzhov/flutter-expandable#36]
If ExpandablePanel gets initialized with an external controller, the build causes a runtime error as ExpandableButton cannot find a controller ancestor and tries to call a method on null.

This is caused by a small error in the _ExpandableNotifierState:initState() method, where the code checks for widget.controller null value and fails to initialize the state's controller field. The solution is to remove the if statement around the controller initialization:
```
void initState() {
    super.initState();
    //if (widget.controller == null) {
    controller = widget.controller ??
        ExpandableController(initialExpanded: widget.initialExpanded ?? false);
    //}
  }
```
Please let me know if you need a PR for this.

**Comment by aryzhov** [comment]
Hello, 

Thank you for filing this. I will take a look today.
