### ISSUE TITLE
Change the position of the icon

### ISSUE THREAD

**Issue by HardikkMadaan** [aryzhov/flutter-expandable#37]
I wish to change the position of the arrow icon. Currently it comes in the next line of the specified text. Is there any way i can align it in the same line as of text, to the right of it ?
I'll give an example!
![home screen-2 multiple media in one post – 8](https://user-images.githubusercontent.com/33843351/71377831-d20f9400-25eb-11ea-94ec-5bff9705d1f0.jpg)

**Comment by maheshmnj** [comment]
I had the same issue,use this ``` headerAlignment: ExpandablePanelHeaderAlignment.center;``` 
this will align the header to center ,however this is deprecated with the latest version of the plugin but gets the work done

**Comment by aryzhov** [comment]
The proper way to do it in the latest release is in theme data:
```dart
ExpandablePanel(
    theme: ExpandableThemeData(headerAlignment: ExpandablePanelHeaderAlignment.bottom),
    ...
)
```
