### ISSUE TITLE
AndroidManifest.xml could not be found.

### ISSUE THREAD

**Issue by Dzunior** [aryzhov/flutter-expandable#40]
Hi, I'm trying to run an example (after git cloning ).
Getting following error:

`Launching lib/main.dart on Android SDK built for x86 64 in debug mode...
AndroidManifest.xml could not be found.
Please check /home/dominik/Flutter_projects/flutter-expandable/example/android/AndroidManifest.xml for errors.
No application found for TargetPlatform.android_x64.
Is your project missing an android/AndroidManifest.xml?
Consider running "flutter create ." to create one.`

How can I run it?

**Comment by aryzhov** [comment]
It tells you right there: flutter create .

You need to run that command because it generates platform-specific files
that aren’t necessary to put into git.

**Comment by Samanbah** [comment]
when i run "flutter create ." i have this erorr
Oops; flutter has exited unexpectedly: "FileSystemException: Cannot create file, path = 'C:\Windows\System32\.gitignore'(OS Error: Access is denied.
, errno = 5)".

A crash report has been written to C:\Users\anf\AppData\Local\Temp\flutter_tools.b6652c61\flutter_01.log.
what should i do now?
