### ISSUE TITLE
tapBodyToCollapse to expand body problem

### ISSUE THREAD

**Issue by gbmiranda** [aryzhov/flutter-expandable#43]
Hello, I have a problem with the tapBodyToCollapse property. I can't expand by clicking on the body if I click on any container. To minimize it works normal.

**Comment by aryzhov** [comment]
The `tapBodyOnCollapse` property works only for collapsing, not for expanding. This question has been brought up before, see #41, where I explained why and described a workaround.

**Comment by gbmiranda** [comment]
I understand your point. in my specific case and I believe that for some that possibility would be interesting.

**Comment by aryzhov** [comment]
I added this feature to version 4.1.0 that has been released. You can specify this property in the theme.
