### ISSUE TITLE
Splash effect not clippable/cannot be rounded

### ISSUE THREAD

**Issue by andrewjallenuoft** [aryzhov/flutter-expandable#45]
A small cosmetic issue, but it seems that there is no way to round the corners of the splash effect on the header of the expandable panel. Placing a ClipRRect above the expandable panel widget will only clip the content, but the splash effect is not clipped. Setting useInkWell = false in ExpandableThemeData seems to have no effect, with the splash effect still showing.

![image](https://user-images.githubusercontent.com/32487067/73693056-70077b80-46cd-11ea-94cc-02d233f32ae3.png)

**Comment by aryzhov** [comment]
Hello, I will look into the issue. Thank you for reporting.

**Comment by aryzhov** [comment]
Version 4.1.4 has a new theme property: `inkWellBorderRadius`. You can use it to clip the ink well effect.
