### ISSUE TITLE
How can i create expanded only one card at a time

### ISSUE THREAD

**Issue by vinodlee** [aryzhov/flutter-expandable#46]
How can i create expanded card viewed,  only one card at a time, not showed for multiple expanded card

**Comment by aryzhov** [comment]
Your question is identical to issue #8. Currently there is no easy way provided by the plugin, but it's possible to do programmatically. You have to store a list of `ExpandableController` objects corresponding to your list of cards. You have to attach a listener to every one of these controller objects, and when one controllers's value becomes `true`, change the value of the previously expanded controller to `false`.

**Comment by vinodlee** [comment]
Can you send any example **aryzhov** , it's useful for me

**Comment by vinodlee** [comment]
am tried the controller also not working for me any other solution available ?

**Comment by vinodlee** [comment]
or else how can i stop auto-close the card when am scrolling multiple card at list view, help me this **### aryzhov**

**Comment by aryzhov** [comment]
I am keeping issue #8 open and closing this as a duplicate. It's possible to do but I just don't have the time to write an example for this feature right now. I understand that this is an issue for you and I will consider this feedback when prioritizing future work on this package.
