### ISSUE TITLE
GestureDetector inside expanded with setState fires toggle

### ISSUE THREAD

**Issue by js-acevedo10** [aryzhov/flutter-expandable#57]
Hey ! Great library, is there a way to prevent a GestureDetector that I'm placing inside expanded widget, that calls setState((){...}) onTap to toggle the expansion of the widget?

**Comment by aryzhov** [comment]
In this case, you should set `tapBodyToCollapse: false`. If you still want the widget to collapse when the user taps on an area other than your GestureDetector, you can either:
 a) use `ExpandableButton`; or 
 b) have another GestureDetector, and use ExpandableController to collapse the widget in the `onTap` handler.
