### ISSUE TITLE
toggle() doesn't work

### ISSUE THREAD

**Issue by Franco7Scala** [aryzhov/flutter-expandable#58]
When I try to call method toggle on the controller in this way (the controller is null):

```
var controller = ExpandableController.of(context);
controller.toggle();
```

and in this (the controller isn't null) but the toggle function is not executed:

`expandablePanel.controller.toggle();`

I instantiate the panel in this way:

```
ExpandablePanel expandablePanel = ExpandablePanel(
  controller: ExpandableController(),
  expanded: ProductDetailContent(
    product: product,
  )
);
```

**Comment by aryzhov** [comment]
You should call `ExpandableController.of(context)` in the beginning of your build method (not inside a callback function, for example). If that does not work, please make a minimal application that reproduces your issue and submit it here.

**Comment by aryzhov** [comment]
I think I know what the problem is. You are instantiating the controller when you are constructing the panel. Instead, you should either use `ExpandableNotifier`, which is what I recommend, or create and keep the controller in your state object.
