### ISSUE TITLE
Expandable within expandable content isn't animating/fading in

### ISSUE THREAD

**Issue by kbokarius** [aryzhov/flutter-expandable#64]
When placing an expandable within another, we're seeing the sub-expandable header and content blink into existence at the moment the parent slide/fade-in animation is supposed to end. The child expandable animates properly after the parent is already expanded, but when tapping and expanding the parent expandable, the child's header and content aren't shown for the duration of the slide/fade-in animation, then they simply pop into existence.

**Comment by kbokarius** [comment]
This looks like a different bug, not related to this library. When I replace the header and content with simple widgets it seems to work fine.

**Comment by kbokarius** [comment]
It looks like the cause is a Button widget within the child expandable, maybe a Flutter bug?

**Comment by oyvindsam** [comment]
@kbokarius Did you ever solve this? By trial and error I found that Flexible widget messes up my custom widgets, but have not found a way to fix it.

**Comment by kbokarius** [comment]
@oyvindsam no, we had to change the widgets we used within the expandable.
