### ISSUE TITLE
Unable to change icon background color.

### ISSUE THREAD

**Issue by BLKKKBVSIK** [aryzhov/flutter-expandable#67]
<img width="407" alt="Screenshot 2020-08-04 at 13 38 35" src="https://user-images.githubusercontent.com/20175372/89289601-cf801d00-d657-11ea-87c3-0bd72b082d07.png">

There is no option to change the background of the icon when there is `hasIcon: true`

Here's my snippet:
```ExpandablePanel(
          theme: const ExpandableThemeData(
            tapBodyToCollapse: true,
            iconColor: Colors.black,
            tapHeaderToExpand: true,
            hasIcon: true,
            headerAlignment: ExpandablePanelHeaderAlignment.center,
          ),
          header: Container(
            decoration: BoxDecoration(
              borderRadius: BorderRadius.only(
                  topLeft: const Radius.circular(8.0),
                  topRight: const Radius.circular(8.0),
                  bottomLeft: Radius.circular(animatedContainerBorders),
                  bottomRight: Radius.circular(animatedContainerBorders)),
              color: isActivated ? mainPink : Colors.white,
            ),
            padding: const EdgeInsets.symmetric(vertical: 25.0),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Flexible(
                  flex: 5,
                  child: Center(child: Text(widget.text.toUpperCase())),
                ),
              ],
            ),
          ),
          expanded: Container(
            padding: const EdgeInsets.symmetric(vertical: 10.0),
            child: Text("Blabla"),
          )
       ),```

**Comment by BLKKKBVSIK** [comment]
I finally decided to implement it myself by recreating the animated icon

**Comment by udaykumaruking** [comment]
> I finally decided to implement it myself by recreating the animated icon


Can you help me out by sharing the code

**Comment by BLKKKBVSIK** [comment]
> > I finally decided to implement it myself by recreating the animated icon
> 
> Can you help me out by sharing the code

Unfortunately, I don't have the code anymore.

**Comment by udaykumaruking** [comment]
> > > I finally decided to implement it myself by recreating the animated icon
> > 
> > 
> > Can you help me out by sharing the code
> 
> Unfortunately, I don't have the code anymore.

Oh Okay, Thanks.
