### ISSUE TITLE
Null-safety?

### ISSUE THREAD

**Issue by tsinis** [aryzhov/flutter-expandable#79]
Hey @aryzhov!

Not an Issue actually, but do you have any plans on null-safety migration? Do you accept PRs (not sure if I will find a time for it, but maybe...)? Thanks for a great package!

Wish you all the best in New Year. С наступившим!

**Comment by Sameerkash** [comment]
If there's no WIP on this, I'd be happy to make a PR.

**Comment by msoham123** [comment]
@Sameerkash Now that flutter 2.0 is out, are you still down to make the PR?

**Comment by Sameerkash** [comment]
> @Sameerkash Now that flutter 2.0 is out, are you still down to make the PR?

Yes surely! 
I'll get it up asap.

**Comment by mattia098** [comment]
Some news?

**Comment by aryzhov** [comment]
Version 5.0.1 has been released with null safety. Enjoy!
