### ISSUE TITLE
Does flutter expandable recycle views?

### ISSUE THREAD

**Issue by d-apps** [aryzhov/flutter-expandable#9]
I building an app that have a screen with ExpandablePanel inside another ExpandablePanel with big lists of Strings (Images (small sizes) and texts), I would like to know if expandable recycle views or my app will probably crash, but in that screen I'm building I needed to show all data.

ExpandablePanel -> ExpandablePanel -> Header -> Expanded

Rows (Images and texts) ->  Rows (Images and texts) -> Description (big and small texts)

Thank you.

**Comment by aryzhov** [comment]
Expandable accepts two widgets: expanded and collapsed. These widgets are reused between the states of Expandable.

**Comment by d-apps** [comment]
Thank you.
