### ISSUE TITLE
Disable only one of expansion out of many expansions

### ISSUE THREAD

**Issue by didiarish** [aryzhov/flutter-expandable#92]
Is is possible to disable an expansion to collapse when tap?

**Comment by SickFob** [comment]
I had the same use case and I managed to make it work by wrapping the `ExpandablePanel `with a `IgnorePointer` widget. I hope this might work for you as well.

```
IgnorePointer(
  ignoring: true,
  child: ExpandablePanel()
)
```

For more information about IgnorePointer, check the [docs](https://api.flutter.dev/flutter/widgets/IgnorePointer-class.html)

**Comment by didiarish** [comment]
thankyou @SickFob
